import{a as v,S as B,i}from"./assets/vendor-CMPCLshm.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();v.defaults.baseURL="https://pixabay.com/api/";let g=1;async function L(o,t={}){const s={key:"49149625-6c85390ad8fbd016bc28c7d7b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:g,...t};try{const n=await v.get("",{params:s});return g+=1,n.data}catch(n){throw console.error("Error fetching data from Pixabay API:",n),n}}function x(){g=1}let O=new B(".gallery a",{captions:!0,captionsData:"alt",captionType:"attr",captionDelay:250,animationSpeed:350,captionPosition:"bottom"});function S(){O.refresh()}function w(o){console.log("Дані для рендерингу:",o);const t=document.querySelector(".gallery"),s=o.map(n=>{const{webformatURL:e,largeImageURL:r,likes:c,views:C,tags:q,comments:I,downloads:P}=n,u=document.createElement("li");u.classList.add("gallery-item");const m=document.createElement("a");m.classList.add("gallery-link"),m.href=r;const a=document.createElement("img");a.classList.add("gallery-image"),a.src=e,a.alt=q,a.width=360,a.height=200,u.appendChild(m),m.appendChild(a);const h=document.createElement("div");return h.classList.add("gallery-item-info"),h.innerHTML=`
  <div class="item-info-container">
    <span class="description-name">Likes</span>
    <span class="description-counts">${c}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Views</span>
    <span class="description-counts">${C}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Comments</span>
    <span class="description-counts">${I}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Downloads</span>
    <span class="description-counts">${P}</span>
  </div>
`,u.appendChild(h),u});t.append(...s)}function U(){const o=document.querySelector(".gallery");o.innerHTML=""}const E="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEYSURBVHgBrZZRDoIwDIYrwfDqTeQo3ohxEr0BXsW77GXFOFdkYcC6DuFPCJB1/7fCWgBgZEzfIPY256BYzqfkzE8nUNbCE+DzgqSKK8W6OVBV5xYk+ZUbgw/IFMVKmfxtng3ZYy5CjjBnISlzrXUtGcZiZpDxolsGIWItvTi/OK0xAuk7GhsBRjEGioNMmffMXKNEAAeRzENACYJc8QxF5IuJNBZhS2PSfBGwhNB9rjmpgHxZ5jqprAyC3jT0mi29RwSE5v6xhO9EhAjblN0tqS38G59t02ShKeCzU2Kh+SDE9z0GAUGxGPKaLS4F2aqVudcRENb8CIhovgeSMl/VwdQWbOPOl5yPvivs25b2MWjKJOu3hTX+AgZ5PpvL0NSkAAAAAElFTkSuQmCC",A=document.querySelector(".form"),p=document.querySelector(".loader");document.querySelector(".gallery");const d=document.querySelector(".load-more"),f={message:"Sorry, there are no images matching your search query.Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:E},b={message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:E};A.addEventListener("submit",N);d.addEventListener("click",R);let y=0,l=0;function N(o){o.preventDefault();const t=o.currentTarget.elements.searchQuery.value.trim();t&&(p.classList.remove("visually-hidden"),U(),A.reset(),x(),l=0,L(t).then(s=>{const n=s.hits;if(y=s.hits,l=n.length,n.length===0){i.show(f);return}w(s.hits),S(),l>=y?(i.show(b),d.classList.add("visually-hidden")):d.classList.remove("visually-hidden")}).catch(s=>{i.show(f)}).finally(()=>{p.classList.add("visually-hidden")}))}function R(){const o=A.elements.searchQuery.value.trim();p.classList.remove("visually-hidden"),L(o).then(t=>{const s=t.hits;if(l+=s.length,s.length===0){i.show(f),d.classList.add("visually-hidden");return}w(t.hits),S(),l>=y&&(i.show(b),d.classList.add("visually-hidden"))}).catch(t=>{i.show(f)}).finally(()=>{p.classList.add("visually-hidden")})}
//# sourceMappingURL=index.js.map
