import{a as v,S as x,i}from"./assets/vendor-CMPCLshm.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();v.defaults.baseURL="https://pixabay.com/api/";let y=1;async function L(s,t={}){const o={key:"49149625-6c85390ad8fbd016bc28c7d7b",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:y,...t};try{const r=await v.get("",{params:o});return y+=1,r.data}catch(r){throw console.error("Error fetching data from Pixabay API:",r),r}}function O(){y=1}let U=new x(".gallery a",{captions:!0,captionsData:"alt",captionType:"attr",captionDelay:250,animationSpeed:350,captionPosition:"bottom"});function w(){U.refresh()}function S(s){const t=document.querySelector(".gallery"),o=s.map(r=>{const{webformatURL:e,largeImageURL:a,likes:c,views:I,tags:P,comments:q,downloads:B}=r,u=document.createElement("li");u.classList.add("gallery-item");const m=document.createElement("a");m.classList.add("gallery-link"),m.href=a;const n=document.createElement("img");n.classList.add("gallery-image"),n.src=e,n.alt=P,n.width=360,n.height=200,u.appendChild(m),m.appendChild(n);const h=document.createElement("div");return h.classList.add("gallery-item-info"),h.innerHTML=`
  <div class="item-info-container">
    <span class="description-name">Likes</span>
    <span class="description-counts">${c}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Views</span>
    <span class="description-counts">${I}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Comments</span>
    <span class="description-counts">${q}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Downloads</span>
    <span class="description-counts">${B}</span>
  </div>
`,u.appendChild(h),u});t.append(...o)}function N(){const s=document.querySelector(".gallery");s.innerHTML=""}const E="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEYSURBVHgBrZZRDoIwDIYrwfDqTeQo3ohxEr0BXsW77GXFOFdkYcC6DuFPCJB1/7fCWgBgZEzfIPY256BYzqfkzE8nUNbCE+DzgqSKK8W6OVBV5xYk+ZUbgw/IFMVKmfxtng3ZYy5CjjBnISlzrXUtGcZiZpDxolsGIWItvTi/OK0xAuk7GhsBRjEGioNMmffMXKNEAAeRzENACYJc8QxF5IuJNBZhS2PSfBGwhNB9rjmpgHxZ5jqprAyC3jT0mi29RwSE5v6xhO9EhAjblN0tqS38G59t02ShKeCzU2Kh+SDE9z0GAUGxGPKaLS4F2aqVudcRENb8CIhovgeSMl/VwdQWbOPOl5yPvivs25b2MWjKJOu3hTX+AgZ5PpvL0NSkAAAAAElFTkSuQmCC",b=document.querySelector(".form"),f=document.querySelector(".loader");document.querySelector(".gallery");const d=document.querySelector(".load-more"),g={message:"Sorry, there are no images matching your search query.Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:E},C={message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:E};b.addEventListener("submit",R);d.addEventListener("click",D);let A=0,l=0,p="";async function R(s){if(s.preventDefault(),p=s.currentTarget.elements.searchQuery.value.trim(),!!p){f.classList.remove("visually-hidden"),N(),b.reset(),O(),l=0;try{const t=await L(p),o=t.hits;if(A=t.totalHits,l=o.length,o.length===0){i.show(g);return}S(t.hits),w(),l>=A?(i.show(C),d.classList.add("visually-hidden")):d.classList.remove("visually-hidden")}catch{i.show(g)}finally{f.classList.add("visually-hidden")}}}async function D(){f.classList.remove("visually-hidden");try{const s=await L(p),t=s.hits;if(l+=t.length,t.length===0){i.show(g),d.classList.add("visually-hidden");return}S(s.hits),w(),l>=A&&(i.show(C),d.classList.add("visually-hidden"))}catch{i.show(g)}finally{f.classList.add("visually-hidden")}}
//# sourceMappingURL=index.js.map
